name: Live test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/live-test.yaml"

env:
  HOSTNAME: mqtt.nordicsemi.academy

jobs:
  live-test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        ipv:
          - ipv4
          - ipv6
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install WARP client
        if: matrix.ipv == 'ipv6'
        run: |
          sudo apt-get -y update
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp

      - run: sudo warp-cli --accept-tos registration new
        if: matrix.ipv == 'ipv6'

      - run: sudo warp-cli --accept-tos connect
        if: matrix.ipv == 'ipv6'

      - run: sudo warp-cli --accept-tos mode warp
        if: matrix.ipv == 'ipv6'

      - run: |
          response=$(curl -s https://www.cloudflare.com/cdn-cgi/trace/)
          echo "$response"
          if echo "$response" | grep -q "warp=on"; then
            echo "WARP is enabled"
          else
            echo "WARP is not enabled"
            exit 1
          fi
          echo "IPv6: $(sudo curl -s6m8 --retry 3 -A Mozilla https://api.ip.sb/geoip)"
        if: matrix.ipv == 'ipv6'

      - name: fetch TLS certificate (IPv4)
        if: matrix.ipv == 'ipv4'
        run: curl -4 --fail-with-body -v https://${{ env.HOSTNAME }}/${{ env.HOSTNAME }}.pem

      - name: fetch TLS certificate (IPv6)
        if: matrix.ipv == 'ipv6'
        run: curl -6 --fail-with-body -v https://${{ env.HOSTNAME }}/${{ env.HOSTNAME }}.pem

      - name: Run tests
        env:
          IPV: ${{ matrix.ipv }}
          HOSTNAME: ${{ env.HOSTNAME }}
          CERT_PATH: ${{ github.workspace }}/${{ env.HOSTNAME }}.pem
        run: npm test

  website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: https
        run: |
          curl -L --fail-with-body -v https://${{ env.HOSTNAME }}/ > https.html
          diff https.html docs/index.html

  certificate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: npm ci

      - run: node --experimental-transform-types check-certificate-expiry.ts
