name: Live test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/live-test.yaml"

env:
  HOSTNAME: mqtt.nordicsemi.academy
  NODE_NO_WARNINGS: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  live-test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        ipv:
          - ipv4
          # IPv6 is not working anymore with fscarmen/warp-on-actions
          # - ipv6
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Set up WARP
        if: matrix.ipv == 'ipv6'
        uses: fscarmen/warp-on-actions@v1.3
        with:
          stack: ipv6

      - name: fetch TLS certificate (IPv4)
        if: matrix.ipv == 'ipv4'
        run: curl -4 --fail-with-body -v https://${{ env.HOSTNAME }}/${{ env.HOSTNAME }}.pem > ${{ github.workspace }}/${{ env.HOSTNAME }}.pem

      - name: fetch TLS certificate (IPv6)
        if: matrix.ipv == 'ipv6'
        run: curl -6 --fail-with-body -v https://${{ env.HOSTNAME }}/${{ env.HOSTNAME }}.pem > ${{ github.workspace }}/${{ env.HOSTNAME }}.pem

      - name: Run tests
        env:
          IPV: ${{ matrix.ipv }}
          HOSTNAME: ${{ env.HOSTNAME }}
          CERT_PATH: ${{ github.workspace }}/${{ env.HOSTNAME }}.pem
        run: npm run test:e2e

  website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: https
        run: |
          curl -L --fail-with-body -v https://${{ env.HOSTNAME }}/ > https.html
          diff https.html docs/index.html

  certificate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: npm ci

      - run: node --experimental-transform-types check-certificate-expiry.ts
