name: Live test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/live-test.yaml"

env:
  HOSTNAME: mqtt.nordicsemi.academy

jobs:
  # Ensures that the TLS certificate can be fetched
  fetch-cert:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        protocol: [http, https]

    steps:
      - name: fetch TLS certificate
        run: http -v ${{ matrix.protocol }}://${{ env.HOSTNAME }}/${{ env.HOSTNAME }}.crt

  test-mqtt:
    runs-on: ubuntu-latest

    # needs:
    #   - fetch-cert

    strategy:
      matrix:
        ipv: [4, 6]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Set up WARP
        if: matrix.ipv == 6
        uses: fscarmen/warp-on-actions@v1.0

      - name: Run tests (IPv4)
        env:
          IPV: ${{ matrix.ipv }}
          HOSTNAME: ${{ env.HOSTNAME }}
        run: npx tsx --test test.ts
