name: Verify Dockerfile

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Prepare self-signed cert
        working-directory: certs
        run: |
          # CA key and certificate
          openssl genrsa -out CA.key 2048
          openssl req -new -x509 -nodes -key CA.key -sha256 -days 365 -extensions v3_ca -out chain.pem -subj '/OU=Nordic Developer Academy'
          # Server key
          openssl genrsa -out privkey.pem 2048
          # CSR
          openssl req -out server.csr -key privkey.pem -new -subj '/CN=mqtt.academy.nordicsemi.com'
          # Sign CSR
          openssl x509 -req -in server.csr -CA chain.pem -CAkey CA.key -CAcreateserial -out cert.pem -days 365
          sudo chown 105:106 certs/*

      - name: Build image
        run: docker build -t academy-mqtt .

      - name: Run image
        run: docker run -p 1883:1883 -p 8883:8883 -v ./certs:/etc/cert/live/mqtt.nordicsemi.academy/ -d academy-mqtt

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          VALIDATE_TLS_CERT: 0
        run: npx tsx --test test.ts
